package com.domain.carrental.controller;

import com.domain.carrental.dao.CarDAO;
import com.domain.carrental.model.Car;

import java.util.List;

public class CarController {
    private CarDAO carDAO;

    // Constructor
    public CarController() {
        this.carDAO = new CarDAO();
    }

    // Fetch all available cars
    public List<Car> getAvailableCars() {
        return carDAO.getAvailableCars();
    }

    // Add a new car
    public boolean addCar(String brand, String model, int year, double pricePerDay) {
        Car car = new Car(0, brand, model, year, pricePerDay, true); // ID is auto-generated by DB
        return carDAO.addCar(car);
    }
}
