package com.domain.carrental.controller;

import com.domain.carrental.dao.RentalDAO;
import com.domain.carrental.model.Rental;

import java.time.LocalDate;
import java.util.List;

public class RentalController {
    private RentalDAO rentalDAO;

    // Constructor
    public RentalController() {
        this.rentalDAO = new RentalDAO();
    }

    // Create a new rental
    public boolean createRental(int customerId, int carId, LocalDate startDate, LocalDate endDate, double totalPrice) {
        Rental rental = new Rental(0, customerId, carId, startDate, endDate, totalPrice); // ID is auto-generated by DB
        return rentalDAO.createRental(rental);
    }

    // Fetch rentals for a specific customer
    public List<Rental> getRentalsByCustomer(int customerId) {
        return rentalDAO.getRentalsByCustomer(customerId);
    }
}
